package telemetry

import (
	"errors"
	"net/http"
	"time"

	"github.com/reef-pi/reef-pi/controller/storage"
	"github.com/reef-pi/reef-pi/controller/utils"
)


const PasswordStoredPlaceholder = "<stored>"
const AdafruitIOTokenStoredPlaceholder = "<stored>"

func (t *telemetry) GetConfig(w http.ResponseWriter, req *http.Request) {
	fn := func(_ string) (interface{}, error) {
		var c TelemetryConfig
		if err := t.store.Get(t.bucket, DBKey, &c); err != nil {
			return nil, err
		}
		if c.AdafruitIO.Token != "" {
			c.AdafruitIO.Token = AdafruitIOTokenStoredPlaceholder
		}
		if c.Mailer.Password != "" {
			c.Mailer.Password = PasswordStoredPlaceholder
		}
		return &c, nil
	}
	utils.JSONGetResponse(fn, w, req)
}

func (t *telemetry) UpdateConfig(w http.ResponseWriter, req *http.Request) {
	var c TelemetryConfig

	// Try to read the existing config so we can preserve secrets if the UI sends "<stored>"
	var existingConfig TelemetryConfig
	readErr := t.store.Get(t.bucket, DBKey, &existingConfig)

	// "does not exist" is OK (we'll create a new config). Any other error is real.
	if readErr != nil && !errors.Is(readErr, storage.ErrDoesNotExist) {
		utils.ErrorResponse(http.StatusInternalServerError, "Failed to read existing config. Error: "+readErr.Error(), w)
		return
	}

	fn := func(_ string) error {
		// If the client sent placeholders, swap them back to the stored secret (if available).
		// IMPORTANT: this should happen when readErr == nil (i.e. we successfully loaded existingConfig).
		if c.AdafruitIO.Token == AdafruitIOTokenStoredPlaceholder {
			if readErr == nil {
				c.AdafruitIO.Token = existingConfig.AdafruitIO.Token
			} else {
				// no existing config to preserve; don't persist the placeholder
				c.AdafruitIO.Token = ""
			}
		}

		if c.Mailer.Password == PasswordStoredPlaceholder {
			if readErr == nil {
				c.Mailer.Password = existingConfig.Mailer.Password
			} else {
				// no existing config to preserve; don't persist the placeholder
				c.Mailer.Password = ""
			}
		}

		return t.store.Update(t.bucket, DBKey, c)
	}

	utils.JSONUpdateResponse(&c, fn, w, req)
}

func (t *telemetry) SendTestMessage(w http.ResponseWriter, req *http.Request) {
	fn := func(_ string) error {
		_, err := t.Alert("Test email", "This is a test email, generated by reef-pi at: "+time.Now().Format(time.RFC822))
		return err
	}
	utils.JSONDeleteResponse(fn, w, req)
}
